import { readFileSync } from 'fs';
import { Emulator } from '../src/lib/emu/emulator.ts';
import { parsePE } from '../src/lib/pe/index.ts';
const noop = () => {};
const mockCtx = { fillRect: noop, clearRect: noop, strokeRect: noop, fillText: noop, strokeText: noop, measureText: () => ({ width: 8 }), drawImage: noop, putImageData: noop, getImageData: () => ({ data: new Uint8ClampedArray(4) }), createImageData: (w, h) => ({ data: new Uint8ClampedArray(w * h * 4), width: w, height: h }), save: noop, restore: noop, translate: noop, scale: noop, rotate: noop, setTransform: noop, resetTransform: noop, transform: noop, beginPath: noop, closePath: noop, moveTo: noop, lineTo: noop, arc: noop, arcTo: noop, rect: noop, ellipse: noop, fill: noop, stroke: noop, clip: noop, createLinearGradient: () => ({ addColorStop: noop }), createRadialGradient: () => ({ addColorStop: noop }), createPattern: () => null, font: '', textAlign: 'left', textBaseline: 'top', fillStyle: '', strokeStyle: '', lineWidth: 1, lineCap: 'butt', lineJoin: 'miter', globalAlpha: 1, globalCompositeOperation: 'source-over', imageSmoothingEnabled: true, shadowBlur: 0, shadowColor: 'transparent', canvas: null };
const mockCanvas = { width: 640, height: 480, getContext: () => mockCtx, toDataURL: () => '', addEventListener: noop, removeEventListener: noop, style: { cursor: 'default' }, parentElement: { style: { cursor: 'default' } } };
mockCtx.canvas = mockCanvas;
globalThis.document = { createElement: () => mockCanvas, title: '' };
globalThis.OffscreenCanvas = class { constructor(w, h) { this.width = w; this.height = h; } getContext() { return { ...mockCtx, canvas: this }; } };
globalThis.requestAnimationFrame = (cb) => setTimeout(cb, 0);
globalThis.Image = class { set src(_) {} };
globalThis.URL = { createObjectURL: () => '', revokeObjectURL: noop };
globalThis.Blob = class { constructor() {} };
const b = readFileSync('C:/Users/Olivier/Documents/0_Perso/dosbox_d/2nd_real/SECOND.EXE');
const ab = new ArrayBuffer(b.byteLength); new Uint8Array(ab).set(b);
const peInfo = parsePE(ab);
const emu = new Emulator();
emu.screenWidth = 640; emu.screenHeight = 480;
emu.exeName = 'SECOND.EXE'; emu.exePath = 'D:\\SECOND.EXE';
await emu.load(ab, peInfo, mockCanvas);
// Check MCB at 0x8400 BEFORE execution
const t = emu.memory.readU8(0x8400);
const o = emu.memory.readU16(0x8401);
const s = emu.memory.readU16(0x8403);
console.log('MCB@0x8400 BEFORE run: type=0x' + t.toString(16) + ' owner=0x' + o.toString(16) + ' size=0x' + s.toString(16));
const progEnd = 0x1100 + 27041;
console.log('progEnd=0x' + progEnd.toString(16) + ' mcbAddr=0x8400 overlap=' + (progEnd > 0x8400));
